openapi: 3.0.3
info:
  title: Client Management API
  version: 1.0.0
  description: RESTful API for client management operations
  termsOfService: https://mendoz.labs/terms/apis/
  contact:
    name: API Support
    email: api-support@mendoz.labs
    url: https://mendoz.labs/support
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: https://{environment}.api.mendoz.labs:{port}/{basePath}
    description: API Server
    variables:
      environment:
        enum:
          - dev
          - stg
          - prod
        default: dev
        description: Server environment
      port:
        enum:
          - '4000'
          - '8080'
        default: '8080'
      basePath:
        default: api/v1
security:
  - BearerAuth: []
tags:
  - name: clients
    description: Client management operations
paths:
  /clients/search:
    post:
      tags:
        - clients
      summary: Search clients with pagination
      operationId: searchClientsPaginated
      description: Search and filter clients based on various criteria with pagination support
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClientSummaryFilter'
            example:
              clientName: Acme
              deleted: false
              page: 0
              size: 20
              sortBy: clientName
              sortDirection: ASC
      responses:
        '200':
          description: Clients retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientPage'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /clients/search-one:
    post:
      tags:
        - clients
      summary: Search for a single client
      operationId: searchClientOne
      description: Search for a single client based on filter criteria. Returns the first matching result.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClientSummaryFilter'
            example:
              clientNumber: CLT-12345
      responses:
        '200':
          description: Client found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientSummaryDto'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /clients/{id}:
    parameters:
      - name: id
        in: path
        required: true
        description: Client ID
        schema:
          type: integer
          format: int64
          example: 123
    get:
      tags:
        - clients
      summary: Get client by ID
      operationId: getClientById
      description: Retrieve a specific client by its unique identifier
      responses:
        '200':
          description: Client retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientSummaryDto'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
    put:
      tags:
        - clients
      summary: Update client
      operationId: updateClient
      description: Update an existing client
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ClientSummaryDto'
      responses:
        '200':
          description: Client updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientSummaryDto'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
    delete:
      tags:
        - clients
      summary: Delete client
      operationId: deleteClient
      description: Delete a client (soft delete)
      responses:
        '204':
          description: Client deleted successfully
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      name: X-API-Key
      in: header
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    OAuth2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://auth.mendoz.labs/oauth/authorize
          tokenUrl: https://auth.mendoz.labs/oauth/token
          scopes:
            read:clients: Read client information
            write:clients: Create and update clients
            delete:clients: Delete clients
  parameters:
    startDateTime:
      in: query
      name: startDateTime
      description: Fields to consider to filter by start datetime.
      required: false
      schema:
        type: string
        format: date-time
        example: '2017-07-21T17:32:28.000Z'
    endDateTime:
      in: query
      name: endDateTime
      description: Fields to consider to filter by ended datetime.
      required: false
      schema:
        type: string
        format: date-time
        example: '2017-07-21T17:32:28.000Z'
    preferredField:
      in: query
      name: preferredField
      description: Fields to consider to order the elements.
      required: false
      schema:
        type: string
        example: id
        default: id
    status:
      in: query
      name: status
      description: Fields to consider status.
      required: false
      schema:
        type: string
        default: PENDING
        enum:
          - ENDED
          - STARTED
          - CANCELED
          - PENDING
    id:
      in: path
      name: id
      description: Current entity ID.
      required: true
      schema:
        type: string
        example: d815d301-8bae-4dd0-a292-56e0cb7509d6
    token:
      in: header
      name: token
      description: security token
      required: true
      schema:
        type: string
        example: 283jebuiVIVEG&#G#UGFXVVWWVD#h3dndon3j0d1hd119hd&ywyw^YS
  schemas:
    IDModel:
      type: object
      title: IDModel
      required:
        - currentId
      properties:
        currentId:
          type: integer
          format: int64
          example: 1
    AuditModel:
      type: object
      title: AuditModel
      required:
        - createdAt
        - modifiedAt
        - createdBy
        - modifiedBy
      properties:
        createdAt:
          type: string
          format: date-time
          example: '2017-07-21T17:32:28.000Z'
          description: Timestamp when the resource was created
        modifiedAt:
          type: string
          format: date-time
          example: '2017-07-21T17:32:28.000Z'
          description: Timestamp when the resource was last modified
        createdBy:
          type: string
          example: b815d301-8bae-4dd0-a292-56e0cb7509d5
          description: ID of the user who created the resource
        modifiedBy:
          type: string
          example: b815d301-8bae-4dd0-a292-56e0cb7509d5
          description: ID of the user who last modified the resource
    Sort:
      type: object
      title: Sort
      required:
        - sorted
        - unsorted
        - empty
      properties:
        sorted:
          type: boolean
          example: false
        unsorted:
          type: boolean
          example: true
        empty:
          type: boolean
          example: true
    Pageable:
      type: object
      title: Pageable
      required:
        - sort
        - pageNumber
        - pageSize
        - offset
        - paged
        - unpaged
      properties:
        sort:
          $ref: '#/components/schemas/Sort'
        pageNumber:
          type: integer
          format: int64
          example: 0
        pageSize:
          type: integer
          format: int64
          example: 0
        offset:
          type: integer
          format: int64
          example: 0
        paged:
          type: boolean
          example: true
        unpaged:
          type: boolean
          example: true
    PageableExtra:
      type: object
      title: PageableExtra
      required:
        - totalElements
        - totalPages
        - last
        - numberOfElements
        - sort
        - size
        - number
        - first
        - empty
      properties:
        totalElements:
          type: integer
          format: int64
          example: 0
        totalPages:
          type: integer
          format: int64
          example: 0
        last:
          type: boolean
          example: false
        numberOfElements:
          type: integer
          format: int64
          example: 0
        sort:
          $ref: '#/components/schemas/Sort'
        size:
          type: integer
          format: int64
          example: 0
        number:
          type: integer
          format: int64
          example: 0
        first:
          type: boolean
          example: true
        empty:
          type: boolean
          example: false
    AbstractPage:
      allOf:
        - $ref: '#/components/schemas/PageableExtra'
        - type: object
          title: AbstractPage
          required:
            - pageable
          properties:
            pageable:
              $ref: '#/components/schemas/Pageable'
    BaseResponseModel:
      allOf:
        - $ref: '#/components/schemas/IDModel'
        - $ref: '#/components/schemas/AuditModel'
        - type: object
          title: BaseResponseModel
    ClientSummaryDto:
      allOf:
        - $ref: '#/components/schemas/ClientBase'
        - type: object
          title: ClientSummaryDto
          description: Complete client information matching ClientEntity
          required:
            - id
            - clientName
            - clientNumber
          properties:
            externalReferences:
              type: array
              items:
                $ref: '#/components/schemas/ExternalReference'
              description: List of external reference identifiers
    ClientSummaryFilter:
      allOf:
        - $ref: '#/components/schemas/ClientBase'
        - type: object
          title: ClientSummaryFilter
          description: Filter criteria for searching clients
          properties:
            clientName:
              type: string
              description: Filter by client name (partial match)
            externalReferenceType:
              type: string
              description: Filter by external reference type
            externalReferenceValue:
              type: string
              description: Filter by external reference value
            minVersion:
              type: integer
              format: int32
              description: Minimum version number
            maxVersion:
              type: integer
              format: int32
              description: Maximum version number
            page:
              type: integer
              format: int32
              default: 0
              minimum: 0
              description: Page number (0-indexed)
            size:
              type: integer
              format: int32
              default: 20
              minimum: 1
              maximum: 100
              description: Page size
            sortBy:
              type: string
              description: Field to sort by
              default: id
            sortDirection:
              type: string
              enum:
                - ASC
                - DESC
              description: Sort direction
              default: DESC
    ExternalReference:
      allOf:
        - $ref: '#/components/schemas/ExternalReferenceBase'
        - type: object
          title: ExternalReference
          description: External reference for a client matching ExternalReferenceEntity
          required:
            - externalReferenceType
            - externalReferenceValue
    ClientPage:
      type: object
      title: ClientPage
      description: Paginated client search results
      required:
        - content
        - totalPages
        - totalElements
        - size
        - number
        - first
        - last
        - empty
      properties:
        content:
          type: array
          items:
            $ref: '#/components/schemas/ClientSummaryDto'
          description: List of clients
        totalPages:
          type: integer
          format: int32
          description: Total number of pages
        totalElements:
          type: integer
          format: int64
          description: Total number of elements
        size:
          type: integer
          format: int32
          description: Current page size
        number:
          type: integer
          format: int32
          description: Current page number
        first:
          type: boolean
          description: Is this the first page
        last:
          type: boolean
          description: Is this the last page
        empty:
          type: boolean
          description: Is the content empty
    client_AuditModel:
      type: object
      title: AuditModel
      description: Base audit properties matching BaseAuditEntity
      properties:
        createdAt:
          type: string
          format: date-time
          description: Creation timestamp
          readOnly: true
        updatedAt:
          type: string
          format: date-time
          description: Last update timestamp
          readOnly: true
    ClientBase:
      allOf:
        - $ref: '#/components/schemas/client_AuditModel'
        - type: object
          title: ClientBase
          description: Base schema for client properties based on ClientEntity
          properties:
            id:
              type: integer
              format: int64
              description: Unique client identifier
            version:
              type: integer
              format: int32
              description: Entity version for optimistic locking
            clientName:
              type: string
              description: Client name
              maxLength: 255
            clientNumber:
              type: string
              description: Unique client number
              maxLength: 50
            lastUpdateUserId:
              type: integer
              format: int64
              description: ID of user who last updated the client
            deleted:
              type: boolean
              description: Whether client is deleted
              default: false
    ExternalReferenceBase:
      type: object
      title: ExternalReferenceBase
      description: Base properties for external references
      properties:
        externalReferenceType:
          type: string
          description: Type of external reference
          maxLength: 100
        externalReferenceValue:
          type: string
          description: Value of external reference
          maxLength: 255
        lastUpdateUserId:
          type: integer
          format: int64
          description: ID of user who last updated this reference
        deleted:
          type: boolean
          description: Whether this reference is deleted
          default: false
    ErrorResponse:
      type: object
      title: ErrorResponse
      description: Standard error response
      required:
        - timestamp
        - status
        - error
        - message
        - path
      properties:
        timestamp:
          type: string
          format: date-time
          description: Time when the error occurred
          example: '2023-01-01T12:00:00Z'
        status:
          type: integer
          format: int32
          description: HTTP status code
          example: 400
        error:
          type: string
          description: HTTP status text
          example: Bad Request
        message:
          type: string
          description: Detailed error message
          example: Invalid input parameters
        path:
          type: string
          description: API path where the error occurred
          example: /api/v1/clients/search
        details:
          type: array
          description: Additional error details
          items:
            type: string
          example:
            - Field 'clientName' must not be empty
  responses:
    BadRequest:
      description: Bad request - Invalid input parameters
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    InternalServerError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
